// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-brand-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_brand_profile_default = defineTool({
  name: "get_brand_profile",
  title: "Get brand profile",
  description: "Return the signed-in user's brand profile from Ivero: brand name, website, sector, geographic coverage, objectives and contact info.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db(ctx).from("brand_settings").select(
      "brand_name, website, sector, description, objetivos, coverage_type, coverage_city, coverage_state, coverage_region, contact_name, contact_email, contact_phone, updated_at"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "No brand profile yet. Complete onboarding first." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { brand: data }
    };
  }
});

// src/lib/mcp/tools/list-audit-reports.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_audit_reports_default = defineTool2({
  name: "list_audit_reports",
  title: "List AI influence audits",
  description: "List the signed-in user's Ivero audit reports (AI influence diagnostics), most recent first. Returns id, date, overall score, status label, and audited site URL.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max reports to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db2(ctx).from("audit_reports").select("id, created_at, overall_score, status_label, site_url, source").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { reports: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-audit-report.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_audit_report_default = defineTool3({
  name: "get_audit_report",
  title: "Get audit report detail",
  description: "Return the full detail of a single Ivero audit report by id: overall score, per-pillar breakdown, radar data, keyword cloud and per-engine mentions.",
  inputSchema: {
    id: z2.string().describe("Audit report id. Use `list_audit_reports` first, or omit to fetch the most recent.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = db3(ctx);
    let query = client.from("audit_reports").select(
      "id, created_at, site_url, overall_score, status_label, pillar_details, radar_data, keyword_cloud, ai_engines, source"
    ).eq("user_id", ctx.getUserId());
    if (id) query = query.eq("id", id);
    else query = query.order("created_at", { ascending: false });
    const { data, error } = await query.limit(1).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "No audit report found." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { report: data }
    };
  }
});

// src/lib/mcp/tools/list-competitors.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_competitors_default = defineTool4({
  name: "list_competitors",
  title: "List tracked competitors",
  description: "List the signed-in user's tracked competitors in Ivero.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db4(ctx).from("competitors").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: true });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { competitors: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "klscginkmflwanzjxtqy";
var mcp_default = defineMcp({
  name: "ivero-mcp",
  title: "Ivero \u2014 AI Influence Auditor",
  version: "0.1.0",
  instructions: "Ivero audits how AI assistants (ChatGPT, Gemini, Google AI Mode, Claude) mention a brand. Use these read-only tools to fetch the signed-in user's brand profile, competitors and audit reports (overall score, per-pillar breakdown, keyword cloud, per-engine mentions).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_brand_profile_default, list_audit_reports_default, get_audit_report_default, list_competitors_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
